name: Build JAR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: target/*.jar
